quarkus:
  log:
    level: INFO
  hibernate-orm:
    dialect: org.hibernate.dialect.ClickHouseDialect
  datasource:
    db-kind: clickhouse
    username: default
    password:
    jdbc: 
      url: jdbc:clickhouse://localhost:8123/my_db
  graphql:
    showErrorMessage:
      - control.exception.AlreadyExistingException  