quarkus:
  log:
    level: INFO
  hibernate-orm:
    log:
      sql: true
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
    jdbc:
      timezone: UTC
  datasource:
    db-kind: postgresql
    username: user
    password: password
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/my_db
      max-size: 20
#"%prod":
#  quarkus:
#    hibernate-orm:
#      sql-load-script: no-file
#      database:
#        generation: none
mp:
  graphql:
    showErrorMessage:
      - control.exception.AlreadyExistingException  