quarkus:
  log:
    level: INFO
  hibernate-orm:
    dialect: org.hibernate.dialect.ClickHouseDialect
  datasource:
    db-kind: clickhouse
    username: default
    password: flJ2FpIwAb
    jdbc: 
      url: jdbc:clickhouse://192.168.1.81:30123/default
  graphql:
    showErrorMessage:
      - control.exception.AlreadyExistingException  